WIDTH = 800
HEIGHT = 600
FPS = 60

PLAYER_SPEED = 3
DEFAULT_ENEMY_SPEED = 1
PLAYER_MAX_HEALTH = 5

PLAYER_MELEE_RANGE = 70
PLAYER_MELEE_DAMAGE = 1
PLAYER_MELEE_COOLDOWN = 18

PLAYER_RANGED_DAMAGE = 1
PLAYER_RANGED_SPEED = 8
PLAYER_RANGED_COOLDOWN = 14
PLAYER_RANGED_COST = 20
PLAYER_PROJECTILE_RADIUS = 5
PLAYER_PROJECTILE_COUNT = 1

PLAYER_MAX_MANA = 100
PLAYER_MANA_REGEN = 0.35
PLAYER_PICKUP_RANGE = 28

LEVEL_UP_BASE_XP = 5
LEVEL_UP_GROWTH = 1.4
LEVEL_UP_GROWTH_FLAT = 2

UPGRADE_MELEE_RANGE_INC = 25
UPGRADE_PROJECTILE_RADIUS_INC = 2
UPGRADE_DAMAGE_INC = 1
UPGRADE_PROJECTILE_COUNT_INC = 1
UPGRADE_MANA_COST_REDUCE = 2
UPGRADE_MAX_MANA_INC = 30
UPGRADE_MANA_REGEN_INC = 0.15
UPGRADE_RANGED_COOLDOWN_REDUCE = 2
UPGRADE_PICKUP_RANGE_INC = 20
UPGRADE_SPEED_INC = 0.4
UPGRADE_HEALTH_INC = 1
UPGRADE_HEAL_ON_GAIN = 1
UPGRADE_MELEE_COOLDOWN_REDUCE = 2

MIN_RANGED_MANA_COST = 1
MIN_RANGED_COOLDOWN = 4
MIN_MELEE_COOLDOWN = 6
MAX_PROJECTILE_COUNT = 6
SPECIAL_MELEE_RANGE = 360

ENEMY_MAX_HEALTH = 3
ENEMY_CONTACT_DAMAGE = 1
ENEMY_CONTACT_COOLDOWN = 30
ENEMY_SPEED_CAP = 4.5
ENEMY_SPEED_PER_MIN = 0.18
ENEMY_SPEED_PER_ROUND = 0.10
ENEMY_HP_GROWTH_PER_ROUND = 1.20
ENEMY_HP_GROWTH_PER_MIN = 1.05
ENEMY_TYPE_STATS = {
    "undead": {
        "speed_mult": 1.25,
        "health_mult": 0.85,
    },
    "demon": {
        "speed_mult": 1.0,
        "health_mult": 1.0,
    },
    "orc": {
        "speed_mult": 0.72,
        "health_mult": 1.8,
    },
}

PICKUP_SIZE = 12
GOLD_PER_PICKUP = 1
XP_PER_PICKUP = 1

SPAWN_MARGIN = 50

ENEMY_SCALE_FACTOR = 2
PLAYER_SCALE_FACTOR = 2
FLOOR_TILE_SCALE_FACTOR = 2

PUSHBACK_DISTANCE = 80
ENEMY_KNOCKBACK_SPEED = 5
